package com.reservenook.security.domain

enum class SecurityAuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_RATE_LIMITED,
    LOGOUT_SUCCESS,
    SESSION_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_RATE_LIMITED,
    PASSWORD_RESET_COMPLETED,
    ACTIVATION_RESEND_REQUESTED,
    ACTIVATION_RESEND_RATE_LIMITED,
    PLATFORM_POLICY_UPDATED,
    COMPANY_PROFILE_UPDATED,
    COMPANY_MARKED_INACTIVE,
    COMPANY_INACTIVITY_NOTICE_SENT,
    COMPANY_INACTIVITY_NOTICE_FAILED,
    COMPANY_DELETION_WARNING_SENT,
    COMPANY_DELETION_WARNING_FAILED,
    COMPANY_DELETED,
    COMPANY_DELETION_FAILED
}
