package com.reservenook.security.domain

enum class SecurityAuditEventType {
    LOGIN_FAILURE,
    LOGIN_RATE_LIMITED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_RATE_LIMITED,
    PASSWORD_RESET_COMPLETED,
    ACTIVATION_RESEND_REQUESTED,
    ACTIVATION_RESEND_RATE_LIMITED,
    PLATFORM_POLICY_UPDATED,
    COMPANY_PROFILE_UPDATED
}
