create table dining_areas (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    name varchar(120) not null,
    display_order integer not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_dining_areas_company foreign key (company_id) references companies(id)
);

create table restaurant_tables (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    dining_area_id bigint not null,
    label varchar(120) not null,
    min_party_size integer not null,
    max_party_size integer not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_restaurant_tables_company foreign key (company_id) references companies(id),
    constraint fk_restaurant_tables_area foreign key (dining_area_id) references dining_areas(id)
);

create table restaurant_table_combinations (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    primary_table_id bigint not null,
    secondary_table_id bigint not null,
    created_at timestamp with time zone not null,
    constraint fk_restaurant_table_combinations_company foreign key (company_id) references companies(id),
    constraint fk_restaurant_table_combinations_primary foreign key (primary_table_id) references restaurant_tables(id),
    constraint fk_restaurant_table_combinations_secondary foreign key (secondary_table_id) references restaurant_tables(id),
    constraint uq_restaurant_table_pair unique (primary_table_id, secondary_table_id)
);

create table restaurant_service_periods (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    name varchar(120) not null,
    day_of_week varchar(16) not null,
    opens_at time not null,
    closes_at time not null,
    slot_interval_minutes integer not null,
    reservation_duration_minutes integer not null,
    min_party_size integer not null,
    max_party_size integer not null,
    booking_window_days integer not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_restaurant_service_periods_company foreign key (company_id) references companies(id)
);

create table restaurant_reservations (
    id bigint generated by default as identity primary key,
    booking_id bigint not null unique,
    company_id bigint not null,
    service_period_id bigint not null,
    reserved_at timestamp with time zone not null,
    reserved_until timestamp with time zone not null,
    party_size integer not null,
    status varchar(24) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_restaurant_reservations_booking foreign key (booking_id) references bookings(id),
    constraint fk_restaurant_reservations_company foreign key (company_id) references companies(id),
    constraint fk_restaurant_reservations_service_period foreign key (service_period_id) references restaurant_service_periods(id)
);

create table restaurant_reservation_tables (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null,
    restaurant_table_id bigint not null,
    constraint fk_restaurant_reservation_tables_reservation foreign key (reservation_id) references restaurant_reservations(id),
    constraint fk_restaurant_reservation_tables_table foreign key (restaurant_table_id) references restaurant_tables(id),
    constraint uq_restaurant_reservation_table unique (reservation_id, restaurant_table_id)
);
