create table widget_usage_events (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    origin_host varchar(255) not null,
    event_type varchar(64) not null,
    created_at timestamp with time zone not null,
    constraint fk_widget_usage_events_company foreign key (company_id) references companies(id)
);
