package com.reservenook.operations.application

data class OperationsAlertMessage(
    val subject: String,
    val title: String,
    val intro: String,
    val details: Map<String, String>,
    val actionLabel: String? = null,
    val actionUrl: String? = null,
    val footerNote: String = "This operational alert was generated by ReserveNook."
)

interface OperationsAlertSender {
    fun sendAlert(recipientEmail: String, message: OperationsAlertMessage)
}
